name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 * * 0,4' # Har Sunday aur Thursday ko auto run hoga
  workflow_dispatch:      # Isse hume manual "Run" button dikhega

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -i -X GET "https://hidwvmgjbthiepmtdvvi.supabase.co/rest/v1/students_class_3?select=id&limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZHd2bWdqYnRoaWVwbXRkdnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3Nzc5MzcsImV4cCI6MjA3OTM1MzkzN30.ru-sjp9GLsBkndyJbqQIrTU1BcNN2APVaHeHbDmXIMo" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZHd2bWdqYnRoaWVwbXRkdnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3Nzc5MzcsImV4cCI6MjA3OTM1MzkzN30.ru-sjp9GLsBkndyJbqQIrTU1BcNN2APVaHeHbDmXIMo"
